---
title: "Interim test - version B"
author: "Anthony"
date: today
toc: true
format:
  html:
    embed-resources: true # Quarto HTML document references external files (CSS, JS, images, fonts) as separate files 
    number-sections: true # Automatically adds numbered headings to your document
    code-fold: true #hide or show the code
editor: visual
editor_options:
  chunk_output_type: console #the ouptput is in the console instead of in the document
execute:
  warning: false
  message: false
---

# Prepare the session

```{r}
#| label: prepare-session

# Load packages
  library(pastecs)
  library(ggpubr); theme_set(theme_bw())
  library(GGally)
  library(performance)
  library(MuMIn)
  library(ggeffects)
  library(knitr) 

asthmaTherapy <- read.csv(here::here("BME-321-FS2026-B", "data", "processed", "lung-function.csv"))
View(asthmaTherapy)
```

## Explore data

### Numerically

```{r}
#| label: tbl-explore-data
#| tbl-cap: "Descriptive statistics for the variables of interest."
#| echo: false

# Numerically
 sum_stats<-
   stat.desc(asthmaTherapy)
 
 kable(sum_stats, digits= 1)
```

### Graphically

```{r}
#| label: fig-scatterplot
#| fig-cap: "Scatterplopt matrix of the Therapy data."
#| output: false # i won't render the output
#| echo: false

# Scatterplot matrix
ggpairs(asthmaTherapy)
 
```

```{r}
ggarrange(
  ggplot(asthmaTherapy, aes(x = treatment_group, y = fev1_improvement))+
    geom_point()+
   # geom_point(aes(colour = smoking_status, size = age))+
     geom_smooth(method= lm) ,
  ggplot(asthmaTherapy, aes(x = baseline_fev1, y = fev1_improvement))+
        geom_point()+
   # geom_point(aes(colour = smoking_status, size = age))+
     geom_smooth(method= lm) ,
    ggplot(asthmaTherapy, aes(x = age, y = fev1_improvement))+
        geom_point()+
   # geom_point(aes(colour = smoking_status, size = age))+
     geom_smooth(method= lm) ,
    ggplot(asthmaTherapy, aes(x =smoking_status, y = fev1_improvement))+
        geom_point()+
   # geom_point(aes(colour = smoking_status, size = age))+
     geom_smooth(method= lm)
)
```

## Modelling

### Finding the best model

```{r}
#| label: tbl-linear-model
#| tbl-cap: "Comparison of the models"
#| echo: false
#| 
  mod.00<- lm(fev1_improvement~ 1, asthmaTherapy)
  mod.01<- lm(fev1_improvement~ age + baseline_fev1 + treatment_group + smoking_status, asthmaTherapy)
  mod.02<- lm(fev1_improvement~ age * baseline_fev1 * treatment_group * smoking_status, asthmaTherapy)
  
kable(compare_performance(mod.00, mod.01, mod.02), digits = 3)
```

```{r}

  anova(mod.00, mod.01, mod.02)                                 # F-test
  compare_performance(mod.00, mod.01, mod.02)    
```

```{r}
#| label: fig-diagnostic-plots
#| fig-cap: "Model diagnostics: these look pretty good "
#| echo: false
# Validate model
check_model(mod.02)
```

## Results interpretation

### Numerically 

```{r}
  Anova(mod.02)
  summary(mod.02)
```

### Graphicallly

```{r}
#| label: fig-plot
#| fig-cap: "Raw data and model predictions to visualize the relationship"
#| echo: false
#| output: true

  (pred.baseline<- predict_response(mod.01, "baseline_fev1"))
  (pred.age<- predict_response(mod.01, "age"))


ggarrange(
  ggplot(pred.baseline, aes(x, predicted))+
    geom_point(data= asthmaTherapy, aes(x= baseline_fev1, y=fev1_improvement, colour = smoking_status))+
      labs(y="Improvement", x= expression("baseline (liters)"))+
    geom_line(),
  
  ggplot(pred.age, aes(x, predicted))+
    geom_point(data= asthmaTherapy, aes(x= age, y=fev1_improvement, colour = smoking_status))+
    geom_line()+
      labs(x= "age", y="improvement")
)
```

  

